#
#     Configure how permissions for each badge should look like
#     The format should be "pewbadges.<server>.<season>.<badge>"
#

#Players get this badge when they join the server once
Joined: pewbadges.hardcore.first.joined
#Players get this badge when they complete one advancement
Played: pewbadges.hardcore.first.played
#Players get this badge when they complete the "Free The End" advancement (Kill the Dragon)
DragonSlayer: pewbadges.hardcore.first.dragonslayer
#Players get this permission when they die for the first time
Died: pewbadges.hardcore.first.died
#Players get this permission when they complete the "The Next Generation" advancement (Hold the dragon egg)
HeldEgg: pewbadges.hardcore.first.heldegg