name: ApplyBadgePermissions
version: ${project.version}
main: mc.pewdiepie.applybadgepermissions.ApplyBadgePermissions
api-version: 1.17
depend: [ Vault ]
authors: [ KamosRZ ]
description: This plugin listens for certain events and applies permissions when conditions for various badges are met.
permissions:
  pewbadges.*:
    description: Registers the custom permissions
